apiVersion: v1
kind: Service
metadata:
  labels:
    app: cddemo
  name: cddemo
  namespace: demo
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: cddemo-instance